max_width = 80
error_on_line_overflow = true
fn_single_line = true
format_strings = true
imports_indent = "Visual"
indent_style = "Visual"
overflow_delimited_expr = true
report_todo = "Always"
struct_field_align_threshold = 20
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
